//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDonPizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelanggan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pelanggan()
        {
            this.Pembayarans = new HashSet<Pembayaran>();
        }
    
        public int Id_pelanggan { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nama_lengkap { get; set; }
        public string nohp { get; set; }
        public string alamat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pembayaran> Pembayarans { get; set; }
    }
}
